blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://www.hauntedmc.nl/support
    about: Use support for usage/setup help.
  - name: Security Report
    url: https://github.com/HauntedMC/VelocityHotReloader/security/advisories/new
    about: Report vulnerabilities privately.
